#!/usr/bin/env bash
# generate-hds-report.sh — FR13: emit a defensive, HDS-ready evidence report
# (Markdown) for a deployment, derived from Terraform state/outputs, and commit it
# to axiome-docs/reports/infra/. Fail-closed: any error exits non-zero so the
# deploy pipeline fails (see Feature MIPP-Hosting-Environment.md R7).
#
# Usage:
#   PROVIDER=aws ENVIRONMENT=production scripts/generate-hds-report.sh
#
# Env:
#   PROVIDER       aws | ovh | scaleway          (required)
#   ENVIRONMENT    dev | staging | production     (required)
#   REPORTS_DIR    output dir (default: ../axiome-docs/reports/infra)
#   COMMIT_SHA     deployment/commit id (default: git short SHA of axiome-infra)
set -euo pipefail

# Accept positional args (preferred) or env vars: generate-hds-report.sh <provider> <environment>
PROVIDER="${1:-${PROVIDER:-}}"
ENVIRONMENT="${2:-${ENVIRONMENT:-}}"
: "${PROVIDER:?PROVIDER required (arg 1 or env): aws|ovh|scaleway}"
: "${ENVIRONMENT:?ENVIRONMENT required (arg 2 or env): dev|staging|production}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PROVIDER_ROOT="${REPO_ROOT}/providers/${PROVIDER}"
REPORTS_DIR="${REPORTS_DIR:-${REPO_ROOT}/../axiome-docs/reports/infra}"

TS="$(date -u +%Y-%m-%dT%H%M%SZ)"
COMMIT_SHA="${COMMIT_SHA:-$(git -C "${REPO_ROOT}" rev-parse --short HEAD 2>/dev/null || echo unknown)}"
TF_VERSION="$(terraform version -json 2>/dev/null | sed -n 's/.*"terraform_version": *"\([^"]*\)".*/\1/p' | head -1)"
TF_VERSION="${TF_VERSION:-unknown}"

# Pull whatever the live state exposes; tolerate "no outputs" (pre-apply / plan).
OUTPUTS_JSON="{}"
if [ -d "${PROVIDER_ROOT}" ]; then
  OUTPUTS_JSON="$(terraform -chdir="${PROVIDER_ROOT}" output -json 2>/dev/null || echo '{}')"
fi
get() { echo "${OUTPUTS_JSON}" | jq -r --arg k "$1" '.[$k].value // "—"' 2>/dev/null || echo "—"; }

# Evidence must never contain secrets (FR13 / NFR8). Emit ONLY non-sensitive
# outputs; list sensitive output keys by name, redacted.
NON_SENSITIVE="$(echo "${OUTPUTS_JSON}" | jq -r 'to_entries[] | select(.value.sensitive==false) | "- " + .key + ": " + (.value.value | tostring)' 2>/dev/null || true)"
[ -z "${NON_SENSITIVE}" ] && NON_SENSITIVE="- (no non-sensitive outputs available)"
SENSITIVE_KEYS="$(echo "${OUTPUTS_JSON}" | jq -r '[to_entries[] | select(.value.sensitive==true) | .key] | join(", ")' 2>/dev/null || true)"
[ -z "${SENSITIVE_KEYS}" ] && SENSITIVE_KEYS="(none)"

REGION_DEFAULT="—"
case "${PROVIDER}" in
  aws) REGION_DEFAULT="eu-west-3" ;;
  ovh) REGION_DEFAULT="GRA11" ;;
  scaleway) REGION_DEFAULT="fr-par" ;;
esac

mkdir -p "${REPORTS_DIR}"
REPORT="${REPORTS_DIR}/${TS}__${PROVIDER}__${ENVIRONMENT}__${COMMIT_SHA}.md"

cat > "${REPORT}" <<EOF
<!-- AUTO-GENERATED by scripts/generate-hds-report.sh (FR13). Do not hand-edit. -->
# HDS Evidence Report — ${PROVIDER}/${ENVIRONMENT}

| | |
|---|---|
| **Generated (UTC)** | \`${TS}\` |
| **Provider** | \`${PROVIDER}\` |
| **Region** | \`$(get region)\` (expected HDS French region: \`${REGION_DEFAULT}\`) |
| **Environment** | \`${ENVIRONMENT}\` |
| **Deployment / commit** | \`${COMMIT_SHA}\` |
| **Terraform** | \`${TF_VERSION}\` |
| **FQDN** | \`$(get fqdn)\` |

## 1. HDS attestation
- Source: ${PROVIDER^^} HDS attestation (AWS Artifact / OVH / Scaleway) — record reference here.

## 2. Service inventory & HDS scope
Derived from Terraform state (non-sensitive outputs only). Confirm each service is in the provider's HDS-certified scope.

${NON_SENSITIVE}

**Redacted (sensitive — never emitted to evidence):** ${SENSITIVE_KEYS}

## 3. Encryption (FR6 / NFR5)
- Data-at-rest CMK and in-transit TLS per the provider KMS + TLS config. Confirm CMK ids in state.

## 4. Network isolation (NFR7 / AC11)
- Private network + default-deny; data/broker/cache ports reachable only from the app tier; **no 0.0.0.0/0**.

## 5. Data residency (NFR2)
- All stores/keys/logs/compute in the chosen French region. Non-French dependencies: none expected.

## 6. Migration parity (NFR4)
- See the migration Qualification Record (FR14) for this deploy: \`reports/infra/*__qualification.md\`.

## 7. Sign-off (NFR6)
- Environment sign-off: _record reviewer / date before the pilot clock starts._
EOF

# Update the index (newest first).
INDEX="${REPORTS_DIR}/INDEX.md"
if [ ! -f "${INDEX}" ]; then
  printf '# Infra Evidence Index\n\n| Generated (UTC) | Provider | Env | Commit | Report |\n|---|---|---|---|---|\n' > "${INDEX}"
fi
TMP="$(mktemp)"
head -n 4 "${INDEX}" > "${TMP}"
printf '| %s | %s | %s | %s | [report](./%s) |\n' "${TS}" "${PROVIDER}" "${ENVIRONMENT}" "${COMMIT_SHA}" "$(basename "${REPORT}")" >> "${TMP}"
tail -n +5 "${INDEX}" >> "${TMP}"
mv "${TMP}" "${INDEX}"

echo "HDS evidence report written: ${REPORT}"
